spring.application.name=udjcs

spring.datasource.url=jdbc:postgresql://localhost:5432/udjcs
spring.datasource.username=udjcs
spring.datasource.password=udjcs
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.port=8082

app.admin.username=admin
app.admin.password=admin@udjcs

app.upload.dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
